name: Deploy Backend to Docker Hub and Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Decode Firebase Key
      run: echo "$GOOGLE_CREDENTIALS_B64" | base64 -d > serviceAccountKey.json

    - name: Install dependencies
      run: npm install

    - name: Build backend
      run: npm run build

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-backend .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/task-backend

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
