

name: Deploy Backend Functions to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install function dependencies
    
      run: cd functions && npm install

    - name: Build backend (Cloud Functions)
    
      run: cd functions && npm run build

    - name: Decode Google Cloud credentials and authenticate
      env:
        GCP_SA_KEY_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$GCP_SA_KEY_BASE64" | base64 --decode > /tmp/gcp_sa_key.json

    - name: Show first 5 lines of decoded JSON key (TEMPORAL - REMOVER DESPUÉS)
      run: |
        echo "Primeras líneas de la clave JSON decodificada (¡NO COMPARTIR!):"
        head -n 5 /tmp/gcp_sa_key.json
        echo "..."

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "$(cat /tmp/gcp_sa_key.json)"

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firebase Cloud Functions
    
      run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project task-app-293dd